import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import jspdf, { jsPDF } from 'jspdf';  
import html2canvas from 'html2canvas';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import {MatButtonModule} from '@angular/material/button';
import {MatIconModule} from '@angular/material/icon';
import { CommonModule } from '@angular/common';
import { FormControl, FormsModule } from '@angular/forms';
import {MatSelectModule} from '@angular/material/select';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatGridListModule} from '@angular/material/grid-list';
import {MatCardModule} from '@angular/material/card';
import {DateAdapter, MAT_DATE_FORMATS, provideNativeDateAdapter} from '@angular/material/core';
import {MatDatepickerModule} from '@angular/material/datepicker';
import { GRI_DATE_FORMATS } from './core/helpers/date-format';
import { MatInputModule } from '@angular/material/input';
import {MatDividerModule} from '@angular/material/divider';
import * as constants from './core/constants/const';

@Component({
  selector: 'app-root',
  imports: [
    MatSlideToggleModule,
    MatButtonModule,
    MatIconModule,
    CommonModule,
    FormsModule,
    MatSelectModule,
    MatFormFieldModule,
    MatGridListModule,
    MatCardModule,
    MatDatepickerModule,
    MatInputModule,
    MatDividerModule,
  ],
  providers: [provideNativeDateAdapter(),
    { provide: MAT_DATE_FORMATS, useValue: GRI_DATE_FORMATS }
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})

export class AppComponent implements OnInit {

  name = 'Delkia';

  currentDate = new Date();
  dateStart = new Date();
  dateEnd = new Date();

  techList = constants.techniciens;
  selectedTech: string[] = [constants.techniciens[0]];

  toppings = new FormControl('');
  toolsList: string[] = constants.tools;
  selectedTools: string[] = [];

  typesList: string[] = constants.types;
  selectedType = 'Mode opératoire';

  interventionPlace = '';
  pdpNumber = '';

  constructor(private readonly adapter: DateAdapter<Date>) {}
            
  ngOnInit(): void {
    
    this.adapter.setLocale('fr-FR'); // Set the locale to French  
  }

  generatePDF() {
    const data = document.getElementById('contentToConvert');
    
    console.log(data);
    if(data !== null) {
      html2canvas(data, {scale: 2}).then(canvas => {
        const pdf = new jsPDF(); // A4 size page of PDF
        pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 210, 297); // A4 size dimensions in mm (210x297)
        
        pdf.setProperties({
          title: 'Delkia-' + this.currentDate,
          subject: 'Dynamic Data PDF', 
          author: 'André Stoclin',
        });
        pdf.setFontSize(12);
        //pdf.text('Generated by Delkia', 14, 22);

        pdf.save('Delkia' + this.currentDate +'.pdf'); // Generated PDF
      });
    }
  }
}
