import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import jspdf, { jsPDF } from 'jspdf';  
import html2canvas from 'html2canvas';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import {MatButtonModule} from '@angular/material/button';
import {MatIconModule} from '@angular/material/icon';
import { CommonModule } from '@angular/common';
import { FormControl, FormsModule } from '@angular/forms';
import {MatSelectModule} from '@angular/material/select';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatGridListModule} from '@angular/material/grid-list';
import {MatCardModule} from '@angular/material/card';
import {DateAdapter, MAT_DATE_FORMATS, provideNativeDateAdapter} from '@angular/material/core';
import {MatDatepickerModule} from '@angular/material/datepicker';
import { GRI_DATE_FORMATS } from './core/helpers/date-format';
import { MatInputModule } from '@angular/material/input';
import {MatDividerModule} from '@angular/material/divider';
import * as constants from './core/constants/const';
import {ChangeDetectionStrategy, inject, model, signal} from '@angular/core';
import {
  MAT_DIALOG_DATA,
  MatDialog,
  MatDialogActions,
  MatDialogClose,
  MatDialogContent,
  MatDialogRef,
  MatDialogTitle,
} from '@angular/material/dialog';
import { Operation } from './core/models/operation';
import { NewOperationComponent } from './component/new-operation/new-operation.component';
import {CdkDragDrop, CdkDropList, CdkDrag, moveItemInArray} from '@angular/cdk/drag-drop';

@Component({
  selector: 'app-root',
  imports: [
    MatSlideToggleModule,
    MatButtonModule,
    MatIconModule,
    CommonModule,
    FormsModule,
    MatSelectModule,
    MatFormFieldModule,
    MatGridListModule,
    MatCardModule,
    MatDatepickerModule,
    MatInputModule,
    MatDividerModule,
    CdkDropList, 
    CdkDrag
  ],
  providers: [provideNativeDateAdapter(),
    { provide: MAT_DATE_FORMATS, useValue: GRI_DATE_FORMATS }
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})

export class AppComponent implements OnInit {

  name = 'Delkia';

  currentDate = new Date();
  dateStart = new Date();
  dateEnd = new Date();

  techList = constants.techniciens;
  selectedTech: string[] = [constants.techniciens[0]];

  toppings = new FormControl('');
  toolsList: string[] = constants.tools;
  selectedTools: string[] = [];

  typesList: string[] = constants.types;
  selectedType = 'Mode opératoire';

  interventionPlace = '';
  pdpNumber = '';

  ops: Operation[] = [];
  
  readonly dialog = inject(MatDialog);

  constructor(private readonly adapter: DateAdapter<Date>) {}
            
  ngOnInit(): void {
    
    this.adapter.setLocale('fr-FR'); // Set the locale to French  
  }

  generatePDF() {
    const data = document.getElementById('contentToConvert');
    
    console.log(data);
    if(data !== null) {
      html2canvas(data, {scale: 2}).then(canvas => {
        const pdf = new jsPDF(); // A4 size page of PDF
        pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 210, 297); // A4 size dimensions in mm (210x297)
        
        pdf.setProperties({
          title: 'Delkia-' + this.currentDate,
          subject: 'Dynamic Data PDF', 
          author: 'André Stoclin',
        });
        pdf.setFontSize(12);
        //pdf.text('Generated by Delkia', 14, 22);

        pdf.save('Delkia' + this.currentDate +'.pdf'); // Generated PDF
      });
    }
  }

  addOp(): void {
    const operation = {
      rank: this.ops.length + 1,
      name: '',
      manipulation: [],
      prevention: '',
    } as Operation;

    const dialogRef = this.dialog.open(NewOperationComponent, {
      data: operation 
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log(result);
      if (result !== undefined) {
        this.ops.push(result);
        //this.ops.sort((a, b) => a.rank - b.rank);
        console.log(this.ops);
      }
    });
  }

  editOp(operation: Operation): void {
    const dialogRef = this.dialog.open(NewOperationComponent, {
      data: operation 
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log(result);
      if (result !== undefined) {
        const index = this.ops.findIndex(op => op.rank === result.rank);
        if (index !== -1) {
          this.ops[index] = result; // Update the operation in the list
        } else {
          console.error('Operation not found in the list');
        }
        //this.ops.push(result);
        //this.ops.sort((a, b) => a.rank - b.rank);
        console.log(this.ops);
      }
    });
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.ops, event.previousIndex, event.currentIndex);
  }
}
