import { Component, ElementRef, ViewChild } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import jspdf, { jsPDF } from 'jspdf';  
import html2canvas from 'html2canvas';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import {MatButtonModule} from '@angular/material/button';
import {MatIconModule} from '@angular/material/icon';
import { CommonModule } from '@angular/common';
import { FormControl, FormsModule } from '@angular/forms';
import {MatSelectModule} from '@angular/material/select';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatGridListModule} from '@angular/material/grid-list';
import {MatCardModule} from '@angular/material/card';

@Component({
  selector: 'app-root',
  imports: [
    MatSlideToggleModule,
    MatButtonModule,
    MatIconModule,
    CommonModule,
    FormsModule,
    MatSelectModule,
    MatFormFieldModule,
    MatGridListModule,
    MatCardModule
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})

export class AppComponent  {
  name = 'Delkia';

  currentDate = new Date().toLocaleDateString();
  selectedOption = 'André Stoclin';
  toppings = new FormControl('');
  toolsList: string[] = ['Gants', 'Casque', 'Veste', 'Marteau', 'Pince', 'Tournevis', 'Clé à molette', 'Scie', 'Perceuse', 'Lunettes de sécurité', 'Bottes de sécurité', 'Gilet de sécurité'];
  selectedTools: string[] = [];

 generatePDF() {
  console.log('test');
  const data = document.getElementById('contentToConvert');
    
    console.log(data);
    if(data !== null) {
      html2canvas(data, {scale: 2}).then(canvas => {
        const pdf = new jsPDF(); // A4 size page of PDF
        pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, 210, 297); // A4 size dimensions in mm (210x297)
        
        pdf.setProperties({
          title: 'Delkia-' + this.currentDate,
          subject: 'Dynamic Data PDF', 
          author: 'André Stoclin',
        });
        pdf.setFontSize(12);
        //pdf.text('Generated by Delkia', 14, 22);

        pdf.save('Delkia' + this.currentDate +'.pdf'); // Generated PDF
      });
    }
  }
}
